apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team1-dev

resources:
- ../../base
- external-secret.yaml
images:
- name: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-app
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-app
  newTag: 9c9847ba6b52d48453b56ec3754b64691d3dcbd2
